version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
      - data:/var/lib/mysql:cached
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
       - redis-data:/data:cached
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
    - 4444:4444
    - 5900:5900
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'
  web: &app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
      - /tmp
      - /app/log
      - /app/.git
    environment:
      HOME: /app
      RAILS_ENV: development
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    links:
      - db
      - redis
      - mailhog
      - chrome

volumes:
  bundle:
    driver: local
  data:
    driver: local
  redis-data:
    driver: local