# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= Rails.application.credentials.dig(:mysql_local, :database_user) %>
  password: <%= Rails.application.credentials.dig(:mysql_local, :database_password) %>
  host: <%= Rails.application.credentials.dig(:mysql_local, :database_host) %>

development:
  <<: *default
  database: infom_development

test:
  <<: *default
  database: infom_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= Ralis.application.credentials.dig(:mysql, :database_user) %>
  password: <%= Ralis.application.credentials.dig(:mysql, :database_password) %>
  host: <%= Ralis.application.credentials.dig(:mysql, :host) %>
  database: infom_production